ALTER TABLE clients ADD COLUMN IF NOT EXISTS "privacyConsent" BOOLEAN DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "privacyConsentDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "privacyConsentSource" VARCHAR(20) DEFAULT 'website';
